apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-jenkins-argocd
  namespace: argocd 
spec:
  project: default

  source: 
    repoURL: https://github.com/shnartho/go-jenkins-argocd-deployment.git
    targerRevision: HEAD
    path: .
  
  destination:
    server: https://kubernetes.default.svc
    namespace: go-jenkins-argocd-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true