apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-jenkins-argocd-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: go-jenkins-argocd-app
  template:
    metadata:
      labels:
        app: go-jenkins-argocd-app
    spec:
      containers:
        - name: go-jenkins-argocd-app
          image: shnartho/go-jenkins-argocd:11
          ports:
            - containerPort: 80

