apiVersion: v1
kind: Service
metadata:
  name: go-jenkins-argocd-service
spec:
  selector:
    app: go-jenkins-argocd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
